# Generated by Django 3.1.2 on 2021-03-29 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_follower_gallery_gallery_info_template_user_wallet_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummypost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_info', models.CharField(max_length=256)),
                ('creationtime', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postposts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
