# Generated by Django 3.1.2 on 2021-03-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_dummypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummypost',
            name='activedummy',
            field=models.BooleanField(default=True),
        ),
    ]
