# Generated by Django 3.1.2 on 2021-04-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_dummypost_activedummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contactgmail',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='opensea_url',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_des',
            field=models.TextField(null=True),
        ),
    ]
