# Generated by Django 3.1.2 on 2021-04-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_wallet',
            name='galleryinfo',
            field=models.TextField(null=True),
        ),
    ]
