# Generated by Django 3.1.2 on 2021-04-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_user_wallet_galleryinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_wallet',
            name='galleryinfo',
        ),
        migrations.AddField(
            model_name='user',
            name='galleryinfo',
            field=models.TextField(null=True),
        ),
    ]
