# Generated by Django 3.1.2 on 2021-05-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20210422_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gallerybgcolor',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gallerybgimage',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gallerytitle',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
