# Generated by Django 3.1.2 on 2021-05-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20210506_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
