# Generated by Django 3.1.2 on 2021-05-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20210507_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='views',
            field=models.IntegerField(null=True),
        ),
    ]
